name: ReviewTwits Server CI/CD

on:
  push:
    branches:
      - main
      - fix/AWSCICDSettings
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: reviewtwits

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Make application.properties
      run: |
        cd ./src/main/resources
        echo "${{ secrets.DB_SECRET_INFO }}" >> ./application.properties
        cat ./application.properties
      shell: bash

    - name: Set up MariaDB client
      uses: einaregilsson/setup-mariadb@v1

    - name: Connect to MariaDB
      run: mysql --host=reviewtwits.c4ga4pm8tur2.ap-northeast-2.rds.amazonaws.com --user=root --password=rootroot reviewtwits -e "show tables;"

    - name: Build with Gradle
      run: ./gradlew clean build

      # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

      # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy


      # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./reviewtwits.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./reviewtwits.zip s3://$S3_BUCKET_NAME/reviewtwits.zip

      # Deploy
    - name: Code Deploy
      run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name reviewtwits \
          --deployment-group-name reviewtwits-group \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=reviewtwits.zip
