name: ReviewTwits Pull Rquest

on:
  pull_request_target:
    branches:
      - feature/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: echo README
        run: cat README.md
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Make application.properties
        run: |
          cd ./src/main/resources
           echo "${{ secrets.DB_SECRET_INFORMATION }}" >> ./application.properties
          cat ./application.properties
        shell: bash
      - name: Make email.properties
        run: |
          cd ./src/main/resources
           echo "${{ secrets.EMAIL_CONFIG_INFO }}" >> ./email.properties
          cat ./email.properties
        shell: bash
      - name: Make oauth.properties
        run: |
          cd ./src/main/resources
           echo "${{ secrets.OAUTH_KEY }}" >> ./oauth.properties
          cat ./oauth.properties
        shell: bash

      - name : Setup MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          mariadb version: '10.6.8' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'reviewtwits' # Optional, default value is "test". The specified database which will be create
          # mysql root password: ${{ secrets.MARIADB_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: ${{ secrets.MARIADB_USERNAME}} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.MARIADB_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

      - name: Build with Gradle
        env:
          auto-ddl: create
        run: ./gradlew clean build